development:
  adapter: postgresql
  encoding: unicode
  database: octo-rails-dev
  pool: 5
  username: postgres
  password: rubberducky

test:
  adapter: postgresql
  encoding: unicode
  database: octo-rails-test
  pool: 5
  username: postgres
  password: rubberducky